### ISSUE TITLE
DoH servers can only be set at build time; add a runtime configuration.

### ISSUE THREAD

**Issue by yann-morin-1998** [dimkr/nss-tls#40]
Currently, the list of DoH servers is set at build time, and is common to all users running the same nss-tls installation.

Often times, the DNS settings may vary, especially on a laptop that can change networks many times a day, where different DoH settings may be used.

For example, on an enterprise networks, an internal DoH server may be used to resolve internal names. When unplugged from this internal network and tethered to the phone, a completely
different network (mostly public) is used then, and a different set of DoH servers is needed, even more so when roaming.

Additionally, different users on the same machine may want to use different DoH servers, for example to avoid using the same servers as those set by the admin of the machine.

As such, a build-time only setting is inapropriate, and requires a way for runtime settings.

As far as I could see, there is no such provision in the current code.

Please, add a way to specify DoH servers at runtime, for both the system-wide and the per-users daemons.

That a change requires a restart of the daemon (e.g. to re-read the config file, or to pass alternate parameters) would be sufficient as a first step. If it would eventually be entirely hot-reconfigurable would undoubtly be so much better, though! ;-)

**Comment by yann-morin-1998** [comment]
Additionally, it would be nice of the other options could also be set at runtime: whether to use the cache or not, whether to use the deterministic mode or not.

**Comment by dimkr** [comment]
Thanks for the recommendations, I'll start working on them, one-by-one. It will take time, though.

**Comment by dimkr** [comment]
> whether to use the cache or not

That's probably the easiest thing to do, because root's nss-tlsd instance has no cache. I'll just need to change the condition from `root` to `root || --no-cache`.

**Comment by dimkr** [comment]
Please see #42

**Comment by yann-morin-1998** [comment]
@dimkr Woot, that's great! :-)

I'll sure take a look at this branch in the following days.

**Comment by dimkr** [comment]
Feel free to open issues if you have more requests, but please put every action item in a separate issue so I can better manage my time and track the progress.

**Comment by dimkr** [comment]
#44 makes nss-tls hot-reconfigurable.
