### ISSUE TITLE
nss-tlsd is not available to all users if started from root

### ISSUE THREAD

**Issue by nick87720z** [dimkr/nss-tls#49]
Is it possible, to have system-wide instance without systemd? I tried to get in under gentoo, where I use openrc as by default. I created init.d script for it, but it appears, that 'daemon' instance is not available for anything but root.

It is possible to use tlslookup under shells, started from root by `sudo -u user bash`. But it is not case for desktop user session, nor for portage processes, where I have as much as possible activity running under dedicated 'portage' user. And if I can solve desktop problem by running nss-tlsd from desktop command launcher, for system upgrade I have to temporarily enable dns resolver (usually I have it disabled, specifying tlsd servers by ip).

Unfortunally I see no info about permission / access config.

Edit: Reminds RPC case, where server uses FIO ops, whose env is setup by RPC, with only difference that RPC is more likely to present in unix-like system.

**Comment by dimkr** [comment]
If you run `nss-tlsd` as root, there you have your system-wide instance. It drops permissions after initialization.

The system-wide instance must _start_ as root, so it can create a socket accessible to all users.

A way to work around this requirement as a regular user is to make `nss-tlsd` a SUID binary, start as a regular user and let it drop permissions.

Does this answer your question?

**Comment by nick87720z** [comment]
Thanks, it's clear now. I supposed, that it needs systemd just because I don't have/use it, and nss-tlsd is not available to other users if started from root.

Btw, setting SUID and running from my current user really works.

**Comment by dimkr** [comment]
Is this part of `README.md` clear enough?

```
If systemd is present, the installation of nss-tls includes unit files for nss-tlsd.

However, nss-tls does not depend on systemd. When systemd is not present, other means of running a nss-tlsd instance for each user (e.g. xinitrc) and root (e.g. an init script) should be used.
```

**Comment by nick87720z** [comment]
@dimkr, I renamed issue)
According to what I understand - system-wide instance is created just by starting as root. I do it from su session.
However it's still invisible to all users: tlslookup exits immediately, and ping says like "unknown host".

**Comment by dimkr** [comment]
@nick87720z Please check if #50 solves the problem.

Right now, `libnss_tls` checks if `XDG_RUNTIME_DIR` is set. If yes, it uses the socket created by the per-user instance under `$XDG_RUNTIME_DIR`, instead of the fixed path of the socket created by the system-wide instance. __Unprivileged users talk to the system-wide instance only if `XDG_RUNTIME_DIR` is not set__.

This is kinda silly, because on pretty much any modern desktop distro,  `XDG_RUNTIME_DIR` is set. #50 makes the fallback behavior make more sense - if `XDG_RUNTIME_DIR` is set, `libnss_tls` tries the user's instance but if it's not running (= no socket), it falls back to the system-wide instance.

**Comment by nick87720z** [comment]
Thanks, this seems to solve problem.
Edit: You mean, XDG_RUNTIME_DIR way is from master?

**Comment by dimkr** [comment]
> Edit: You mean, XDG_RUNTIME_DIR way is from master?

Yes, master uses either a path derived from `XDG_RUNTIME_DIR`, or the fixed path used by the system-wide instance.
