### ISSUE TITLE
distribution of nss-tls on Debian

### ISSUE THREAD

**Issue by monperrus** [dimkr/nss-tls#53]
Thanks for the great project.

Are there any plan to distribute nss-tls on the Debian package repository?

Best regards, --Martin

**Comment by dimkr** [comment]
Hi Martin, I'd love to have nss-tls in the Debian repositories. However, I'm not a Debian developer. I can easily set up a packagecloud.io repository or PPA, but that wouldn't be much better than compiling yourself (because you still have to do something manually, to get nss-tls installed). Unless someone volunteers to take care of packaging in Debian, I don't a way to make this happen.

**Comment by monperrus** [comment]
I see, thanks for your fast answer!

**Comment by petterreinholdtsen** [comment]
https://www.debian.org/doc/manuals/developers-reference/pkgs.html have some clues on how to get the package into Debian proper.  The first stop is WNPP request, then a package on https://mentors.debian.net/ and finally a request for sponsoring.  See also https://wiki.debian.org/DebianMentorsFaq .

**Comment by kanru** [comment]
I plan to work on a Debian package and filed a ITP bug here: https://bugs.debian.org/958710

I have one question though. Do you plan to tag a released version?

**Comment by dimkr** [comment]
> I have one question though. Do you plan to tag a released version?

Right now there are no behavior-changing changes planned except auto-upgrade to DoH (an open PR) which I can merge to master after I tag a 1.0 (and create a 1.x branch). That feature can go into a 2.0 release.

I already maintain the 0.x branch, where nss-tls uses the JSON-based pseudo-standard. Maintaining a 1.x stable release shouldn't be a problem.

**Comment by kanru** [comment]
Hey, the Debian package has just been accepted to the archive. It builds on all the architectures Debian support: https://buildd.debian.org/status/package.php?p=nss-tls

Now, if you can tag a 1.0 release I can upload it right away :)

**Comment by monperrus** [comment]
excellent! who is the official Debian maintainer of the package?

**Comment by dimkr** [comment]
> Now, if you can tag a 1.0 release I can upload it right away :)

Will do

**Comment by dimkr** [comment]
I also created a 1.x branch, to keep the current codebase as stable as possible. I'll make sure to use a pull request for each change in 1.x, and set up a CI cron job for 1.x.

**Comment by petterreinholdtsen** [comment]
https://tracker.debian.org/pkg/nss-tls show the current maintainer and status of the Debian package.

**Comment by kanru** [comment]
Now that nss-tls is included in Debian I think we can close this issue 😀

**Comment by monperrus** [comment]
That's great thanks a lot.
